version: '3'

services:
  database:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABSE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  backend:
    image: jdveloper/so1_back_jun2024:latest
    privileged: true
    pid: host
    container_name: backend_container
    #environment:
      #- DB_HOST:${DB_HOST}
      #- DB_PORT:${DB_PORT}
      #- DB_NAME:${DB_NAME}
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
     - type: bind
       source: /proc
       target: /proc
    restart: always
    depends_on:
      - database
    links:
      - database

  frontend:
    image: jdveloper/so1_front_jun2024:latest
    container_name: front_container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - backend
    links:
      - backend

volumes:
  mongo-data:
    external: false
